### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by ramrivera-github** [33lucasant/mercadoLiebre#1]
- [x]  1 - Cumple: El sitio tiene todas las secciones y sus correspondientes elementos.
- [x]  2 - No cumple: El contenido de los artículos esta centrado, pero el tamaño de los iconos es de 40px y no tiene separación.
- [x]  3 - Cumple: El diseño se adapta a diferentes resoluciones de pantalla.
- [x]  4 - Cumple: El sitio si cuenta con una formulario de ingreso.
- [x]  5 - Cumple: El sitio si cuenta con un formulario de login.
- [x]  6 - Cumple: Los registros presentan mensajes de error de acuerdo al tipo de error.
- [x]  7 - Cumple: La barra de búsqueda es un formulario.
- [x]  8 - Cumple: Si se muestran animaciones y propiedades de transición.
- [x]  9 - El sitio cumple con todas las consignas solicitadas por code review, me pareció muy conveniente la configuración de main-header-top-bar para que no se rompa y se mantenga todo centrado. El estilo en general es muy correcto.
- [x]  10 - Podría mejorar el tamaño de los productos, bajar el porcentaje para que no queden desproporcionados al achicar la resolución.

**Comment by 33lucasant** [comment]
Tamaño de los íconos modificados, margen inferior de 10px ya puesto, y mejoré el tamaño de los productos en base a la resolución.
