### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Santiago-Rearte** [33lucasant/mercadoLiebre#2]
- [x] 1. Cumple: El sitio cumple con todos los puntos. El sitio cuenta con todas sus secciones.

- [x]  2. Cumple: El contenido esta centrado y el tamaño de los iconos esta correcto.

- [x] 3. Cumple: El diseño es adaptativo frente a los diferentes dispositivos.

- [x] 4. Cumple: Si posee un formulario de registro.

- [x] 5. Cumple: Si posee un formulario de login.

- [x]  6. Cumple: Los campos presentan mensaje de error de acuerdo al tipo de dato que se solicita.

- [x] 7. Cumple: La barra de búsqueda es un formulario.

- [x] 8. Cumple: Se muestran animaciones y propiedades de transición de CSS.

- [x]  9. El sitio cumplió con todos los puntos solicitados. Además destaco la disposición de los artículos con su capacidad de adaptación a las distintas pantallas y el estilo de los formularios.

- [x]  10. A nivel estético la alineación del texto del copyright (centrarlo).

**Comment by 33lucasant** [comment]
Texto del Copyright centrado.
